### ISSUE TITLE
查找有些文件时，执行报错

### ISSUE THREAD

**Issue by lizzie** [nightink/nff#3]
```
➜  uisvr  nff -f "数字证书"


========== node.js find {数字证书} list ==========


/usr/local/lib/node_modules/nff/node_modules/iconv-lite/lib/index.js:104
                throw new Error("Encoding not recognized: '" + encoding + "' (
                      ^
Error: Encoding not recognized: 'UTF-32LE' (searched as: 'utf32le')
    at Object.getCodec (/usr/local/lib/node_modules/nff/node_modules/iconv-lite/lib/index.js:104:23)
    at Object.decode (/usr/local/lib/node_modules/nff/node_modules/iconv-lite/lib/index.js:34:25)
    at /usr/local/lib/node_modules/nff/index.js:80:24
    at Lazy.<anonymous> (/usr/local/lib/node_modules/nff/node_modules/lazy/lazy.js:91:13)
    at Lazy.<anonymous> (/usr/local/lib/node_modules/nff/node_modules/lazy/lazy.js:73:19)
    at Lazy.emit (events.js:107:17)
    at yieldTo (/usr/local/lib/node_modules/nff/node_modules/lazy/lazy.js:181:18)
    at Lazy.<anonymous> (/usr/local/lib/node_modules/nff/node_modules/lazy/lazy.js:198:17)
    at Lazy.g (/usr/local/lib/node_modules/nff/node_modules/lazy/lazy.js:14:15)
    at Lazy.emit (events.js:129:20)
```

不支持 `UTF-32LE'` ？应该是 `iconv-lite` 的问题

**Comment by nightink** [comment]
嗯 是的 https://github.com/nightink/nff/blob/master/index.js#L78 
0.7.0-beta.1 先做了过滤。之前测过好像是空文件会有这个问题

**Comment by nightink** [comment]
我先发布个 0.7.0-beta.1 吧

**Comment by nightink** [comment]
已发布 `npm install -g nff`

**Comment by lizzie** [comment]
`Encoding not recognized: 'UTF-32BE' (searched as: 'utf32be')`

好多都不支持，`iconv-lite` 只支持这些编码：https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by nightink** [comment]
好的 

那先简单处理：捕获下异常，然后将文件路径和编码格式暴露出来给用户，让用户人肉识别？
